global:
  scrape_interval: 5s  # Collect data every 5 seconds

scrape_configs:
  # Prometheus Self-Monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Flask API Metrics (Rate Limiting)
  - job_name: "flask_api_metrics"
    static_configs:
      - targets: ["host.docker.internal:5001"]

  # Redis Exporter (for monitoring Redis itself)
  - job_name: "redis_exporter"
    static_configs:
      - targets: ["host.docker.internal:9121"]
